<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Process\FakeProcessResult;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ClientDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('clients')->delete();
        DB::table('clients')->insert([
            0 => [
                'name' => 'ALLIED BANKING CORP',
                'brstn' => '10320013',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            1 => [
                'name' => 'AUSTRALIA & NEW ZEALAND BANKING GROUP (ANZ)',
                'brstn' => '10700015',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            2 => [
                'name' => 'ASIA UNITED BANK',
                'brstn' => '11020011',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            3 => [
                'name' => 'BDO UNIBANK, INC.',
                'brstn' => '10530667',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            4 => [
                'name' => 'BANGKO SENTRAL NG PILIPINAS',
                'brstn' => '10030015',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            5 => [
                'name' => 'BANGKOK BANK',
                'brstn' => '10670019',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            6 => [
                'name' => 'BANK OF AMERICA',
                'brstn' => '10120019',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            7 => [
                'name' => 'BANK OF CHINA',
                'brstn' => '11140014',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            8 => [
                'name' => 'BANK OF THE PHILIPPINE ISLANDS (BPI)',
                'brstn' => '10040018',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            9 => [
                'name' => 'BANK OF TOKYO-MITSUBISHI',
                'brstn' => '10460012',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            10 => [
                'name' => 'BANK OF COMMERCE',
                'brstn' => '10440016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            11 => [
                'name' => 'CHINA BANKING CORP (CHINABANK)',
                'brstn' => '10100013',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            12 => [
                'name' => 'CHINA BANK SAVINGS, INC.',
                'brstn' => '11129996',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            13 => [
                'name' => 'CHINA TRUST COMMERCIAL BANK',
                'brstn' => '10690015',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            14 => [
                'name' => 'CITIBANK PHILIPPINES N.A.',
                'brstn' => '10070017',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            15 => [
                'name' => 'CIMB BANK',
                'brstn' => '18010011',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            16 => [
                'name' => 'CTBC BANK',
                'brstn' => '10690015',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            17 => [
                'name' => 'DEVELOPMENT BANK OF THE PHILIPPINES (DBP)',
                'brstn' => '10590018',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            18 => [
                'name' => 'DEUTSCHE BANK',
                'brstn' => '10650013',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            19 => [
                'name' => 'EAST WEST BANK',
                'brstn' => '10620014',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            20 => [
                'name' => 'EQUICOM SAVINGS BANK',
                'brstn' => '10960017',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            21 => [
                'name' => 'EXPORT & INDUSTRY BANK',
                'brstn' => '10860010',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            22 => [
                'name' => 'FIRST CONSOLIDATED BANK',
                'brstn' => '20780012',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            23 => [
                'name' => 'FUJI BANK',
                'brstn' => '10640010',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            24 => [
                'name' => 'GCASH (GLOBE XCHANGE, INC.)',
                'brstn' => '18040010',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            25 => [
                'name' => 'HONGKONG AND SHANGHAI BANK (HSBC)',
                'brstn' => '10060014',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            26 => [
                'name' => 'INDUSTRIAL BANK OF KOREA',
                'brstn' => '11310019',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            27 => [
                'name' => 'ING BANK N.V.',
                'brstn' => '10660029',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            28 => [
                'name' => 'INTERNATIONAL COMMERCIAL BANK OF CHINA',
                'brstn' => '10560019',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            29 => [
                'name' => 'INTL EXCHANGE BANK',
                'brstn' => '10680012',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            30 => [
                'name' => 'JP MORGAN CHASE BANK',
                'brstn' => '10720011',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            31 => [
                'name' => 'KOREA EXCHANGE BANK (KEB HANA BANK)',
                'brstn' => '10710018',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            32 => [
                'name' => 'INTERNATIONAL NEDERLAND BANK',
                'brstn' => '10660016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            33 => [
                'name' => 'LAND BANK OF THE PHILIPPINES (LANDBANK)',
                'brstn' => '10350025',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            34 => [
                'name' => 'MAYBANK',
                'brstn' => '10220016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            35 => [
                'name' => 'MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD',
                'brstn' => '10560019',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            36 => [
                'name' => 'METROPOLITAN BANK & TRUST CO. (METROBANK)',
                'brstn' => '10269996',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            37 => [
                'name' => 'MIZUHO BANK',
                'brstn' => '10640010',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            38 => [
                'name' => 'MUFG BANK',
                'brstn' => '10460012',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            39 => [
                'name' => 'PHILIPPINE BANK OF COMMUNICATION (PBCOM)',
                'brstn' => '10110016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            40 => [
                'name' => 'PHIL TRUST COMPANY (PHILTRUST)',
                'brstn' => '10090039',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            41 => [
                'name' => 'PHILIPPINE NATIONAL BANK (PNB)',
                'brstn' => '10080010',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            42 => [
                'name' => 'PHILIPPINE SAVINGS BANK (PSBANK)',
                'brstn' => '10269996',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            43 => [
                'name' => 'PRUDENTIAL BANK',
                'brstn' => '10150018',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            44 => [
                'name' => 'PHILIPPINE VETERANS BANK (VETERANS BANK)',
                'brstn' => '10330016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            45 => [
                'name' => 'RIZAL COMMERCIAL BANKING CORP (RCBC)',
                'brstn' => '10280014',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            46 => [
                'name' => 'ROBINSONS BANK CORPORATION',
                'brstn' => '11070016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            47 => [
                'name' => 'STANDARD CHARTERED BANK',
                'brstn' => '10050011',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            48 => [
                'name' => 'SECURITY BANK CORPORATION',
                'brstn' => '10140015',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            49 => [
                'name' => 'SHINHAN BANK',
                'brstn' => '11300016',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            50 => [
                'name' => 'STERLING BANK OF ASIA, INC.',
                'brstn' => '11190019',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            51 => [
                'name' => 'SUMITOMO MITSUI BANKING CORPORATION',
                'brstn' => '11280013',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            52 => [
                'name' => 'TONIK DIGITAL BANK',
                'brstn' => '11570011',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            53 => [
                'name' => 'UNION BANK OF THE PHILIPPINES (UBP)',
                'brstn' => '10419995',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            54 => [
                'name' => 'UNITED COCONUT PLANTERS BANK (UCPB)',
                'brstn' => '10299995',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            55 => [
                'name' => 'UNITED OVERSEAS BANK',
                'brstn' => '10270189',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
            56 => [
                'name' => 'YUANTA SAVINGS BANK',
                'brstn' => '11130011',
                'code' => Str::upper(Str::random(6)),
                'address' => Str::random(20),
                'address1' => Str::random(20),
                'user_id' => 1,
            ],
        ]);
    }
}
